//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetPet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Friend
    {
        public int Friend_no { get; set; }
        public string Email { get; set; }
        [DisplayName("好友Email")]
        public string F_Email { get; set; }
        public bool Add_ststus { get; set; }
        [DisplayName("加入時間")]
        public System.DateTime Change_time { get; set; }
        [DisplayName("好友暱稱")]
        public string Nickname { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
