//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetPet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class News
    {
        public int News_no { get; set; }
        [DisplayName("管理者編號")]
        [Required]
        public int Admin_no { get; set; }
        [DisplayName("主旨")]
        [Required]
        public string N_tital { get; set; }
        [DisplayName("內容")]
        [Required]
        public string N_content { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [DisplayName("公告起始日")]
        [Required]
        public System.DateTime N_post_time { get; set; }
        [DisplayName("圖片")]
        public string N_photo { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [DisplayName("公告截止日")]
        [Required]
        public System.DateTime N_post_deadline { get; set; }
        public virtual Admin Admin { get; set; }

    }
}
