//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetPet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Pet
    {
        public int Pet_no { get; set; }
        [DisplayName("信箱")]
        [EmailAddress]
        public string Email { get; set; }
        [DisplayName("品種編號")]
        public int PetVariety_no { get; set; }
        [DisplayName("寵物大名")]
        public string Pet_name { get; set; }
        [DisplayName("寵物性別")]
        public bool Pet_gender { get; set; }
        [DisplayName("寵物照片")]
        public string Pet_photo { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual PetVariety PetVariety { get; set; }
    }
}
