//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetPet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class petpetEntities : DbContext
    {
        public petpetEntities()
            : base("name=petpetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<City_list> City_list { get; set; }
        public virtual DbSet<Friend> Friend { get; set; }
        public virtual DbSet<Like_record> Like_record { get; set; }
        public virtual DbSet<Mail> Mail { get; set; }
        public virtual DbSet<Mail_photo> Mail_photo { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Messenger> Messenger { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Pet> Pet { get; set; }
        public virtual DbSet<PetType> PetType { get; set; }
        public virtual DbSet<PetVariety> PetVariety { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Post_img> Post_img { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Violation_type> Violation_type { get; set; }
        public virtual DbSet<ReportView> ReportView { get; set; }
    }
}
